# Generated by Django 5.0.8 on 2025-03-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_holder',
            field=models.CharField(default='Tolga Toker', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='card_last_four',
            field=models.CharField(default=1234, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='expiry_date',
            field=models.CharField(default=123, max_length=5),
            preserve_default=False,
        ),
    ]
